name: Build

on:
  workflow_run:
    workflows: [Upload]
    types:
      - completed

jobs:
  deploy:
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GH Page
          id: deployment
          uses: actions/deploy-pages@v1
          with:
            folder: dist
